apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: petmatch
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: petmatch/web-app:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://localhost:8080"  # ポートフォワード用
        envFrom:
        - configMapRef:
            name: petmatch-config
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: petmatch
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
