// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "PetMatch API Support",
            "email": "support@petmatch.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "メールアドレスとパスワードでログインし、JWTトークンを発行します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ユーザーログイン",
                "parameters": [
                    {
                        "description": "ログイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "現在のユーザーをログアウトし、リフレッシュトークンを無効化します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ログアウト",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "認証済みユーザーのプロフィール情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "プロフィール取得",
                "responses": {
                    "200": {
                        "description": "User profile",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "リフレッシュトークンを使用して新しいアクセストークンを発行します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "トークンリフレッシュ",
                "parameters": [
                    {
                        "description": "リフレッシュトークン",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "新規ユーザーを登録し、JWTトークンを発行します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ユーザー登録",
                "parameters": [
                    {
                        "description": "登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "JWTトークンの有効性を検証し、ユーザー情報を返します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "トークン検証",
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized or invalid token",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/errors.ErrorCode"
                },
                "details": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "errors.ErrorCode": {
            "type": "string",
            "enum": [
                "AUTH_INVALID_CREDENTIALS",
                "AUTH_USER_NOT_FOUND",
                "AUTH_USER_ALREADY_EXISTS",
                "AUTH_INVALID_TOKEN",
                "AUTH_TOKEN_EXPIRED",
                "AUTH_UNAUTHORIZED",
                "AUTH_INSUFFICIENT_PERMISSIONS",
                "VALIDATION_FAILED",
                "VALIDATION_INVALID_EMAIL",
                "VALIDATION_INVALID_PASSWORD",
                "VALIDATION_PASSWORD_TOO_WEAK",
                "VALIDATION_INVALID_PHONE",
                "VALIDATION_INVALID_REQUEST_BODY",
                "VALIDATION_REQUIRED_FIELD_MISSING",
                "PET_NOT_FOUND",
                "PET_ALREADY_EXISTS",
                "PET_INVALID_STATUS",
                "PET_NOT_AVAILABLE",
                "USER_PROFILE_NOT_FOUND",
                "USER_UPDATE_FAILED",
                "APPLICATION_NOT_FOUND",
                "APPLICATION_DUPLICATE",
                "APPLICATION_CLOSED",
                "FILE_UPLOAD_FAILED",
                "FILE_TOO_LARGE",
                "FILE_INVALID_TYPE",
                "IMAGE_NOT_FOUND",
                "DATABASE_ERROR",
                "DATABASE_CONNECTION_FAILED",
                "DATABASE_QUERY_FAILED",
                "CACHE_ERROR",
                "CACHE_NOT_FOUND",
                "INTERNAL_SERVER_ERROR",
                "NOT_FOUND",
                "BAD_REQUEST",
                "FORBIDDEN",
                "CONFLICT",
                "RATE_LIMIT_EXCEEDED",
                "SERVICE_UNAVAILABLE"
            ],
            "x-enum-varnames": [
                "ErrCodeInvalidCredentials",
                "ErrCodeUserNotFound",
                "ErrCodeUserAlreadyExists",
                "ErrCodeInvalidToken",
                "ErrCodeTokenExpired",
                "ErrCodeUnauthorized",
                "ErrCodeInsufficientPermissions",
                "ErrCodeValidationFailed",
                "ErrCodeInvalidEmail",
                "ErrCodeInvalidPassword",
                "ErrCodePasswordTooWeak",
                "ErrCodeInvalidPhoneNumber",
                "ErrCodeInvalidRequestBody",
                "ErrCodeRequiredFieldMissing",
                "ErrCodePetNotFound",
                "ErrCodePetAlreadyExists",
                "ErrCodeInvalidPetStatus",
                "ErrCodePetNotAvailable",
                "ErrCodeUserProfileNotFound",
                "ErrCodeUserUpdateFailed",
                "ErrCodeApplicationNotFound",
                "ErrCodeApplicationDuplicate",
                "ErrCodeApplicationClosed",
                "ErrCodeFileUploadFailed",
                "ErrCodeFileTooLarge",
                "ErrCodeInvalidFileType",
                "ErrCodeImageNotFound",
                "ErrCodeDatabaseError",
                "ErrCodeDatabaseConnectionFailed",
                "ErrCodeDatabaseQueryFailed",
                "ErrCodeCacheError",
                "ErrCodeCacheNotFound",
                "ErrCodeInternalServerError",
                "ErrCodeNotFound",
                "ErrCodeBadRequest",
                "ErrCodeForbidden",
                "ErrCodeConflict",
                "ErrCodeRateLimitExceeded",
                "ErrCodeServiceUnavailable"
            ]
        },
        "models.UserLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.UserRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "type"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 500
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "adopter",
                        "shelter",
                        "individual"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PetMatch Auth Service API",
	Description:      "認証・認可サービスAPI。ユーザー登録、ログイン、トークン管理を提供します。\n\n**APIバージョニング**:\n- 推奨: `/api/v1/auth/*` (新規実装はこちらを使用)\n- レガシー: `/auth/*` (2025年6月1日に廃止予定)\n\nすべてのレスポンスヘッダーに `X-API-Version: v1` が含まれます。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
