apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: petmatch
  labels:
    app: auth-service
    service: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        service: auth
    spec:
      containers:
      - name: auth-service
        image: petmatch/auth-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: petmatch-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: petmatch-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petmatch-secrets
              key: REDIS_PASSWORD
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: petmatch-secrets
              key: JWT_ACCESS_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: petmatch-secrets
              key: JWT_REFRESH_SECRET
        - name: JWT_ACCESS_TTL
          value: "900"
        - name: JWT_REFRESH_TTL
          value: "604800"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: petmatch
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  type: ClusterIP
